apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-oauth-proxy.fullname" . }}-cookie
  labels:
    {{- include "sso-oauth-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.cookie.secret | b64enc | quote }}
