apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "sso-oauth-proxy.fullname" . }}-oauth
  labels:
    {{- include "sso-oauth-proxy.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:

    - match: Host(`{{ .Values.app.url }}`) && PathPrefix(`/oauth2`)
      kind: Rule
      services:
        - name: {{ include "sso-oauth-proxy.fullname" . }}
          port: {{ .Values.service.port }}
          healthcheck:
            path: /
            host: {{ .Values.app.url }}
            intervalSeconds: 10
            timeoutSeconds: 5
      middlewares:
        - name: {{.Release.Namespace}}-{{ include "sso-oauth-proxy.fullname" . }}-signin@kubernetescrd
        - name: traefik-security@kubernetescrd
  tls: {}