apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "sso-oauth-proxy.fullname" . }}-verify
  labels:
    {{- include "sso-oauth-proxy.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ include "sso-oauth-proxy.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local:{{ .Values.service.port }}/oauth2/auth
    trustForwardHeader: "true"
    authResponseHeaders:
      - Auth-Request-User
      - X-Auth-Request-Email
      - Authorization
      - Set-Cookie
