apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-oauth-proxy.fullname" . }}-oidc-client
  labels:
    {{- include "sso-oauth-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  id: {{ .Values.oidc.client.id }}
  secret: {{ .Values.oidc.client.secret }}
